# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Search for unique species in a matrix of species trait values.
#'
#' @noRd
#'
NULL

#' Strength of selection for traits `V`, ones for resources
#'
#'
#' @noRd
#'
NULL

#' Sets matrix of traits for each resource (<# resources> x <# resources' traits>)
#'
#' @noRd
#'
NULL

#' Strength of selection for traits `U`, ones for consumers
#'
#'
#' @noRd
#'
NULL

#' Sets traits for each consumer (<# consumers> x <# consumers' traits>)
#'
#'
#' @noRd
#'
NULL

#' One trial of iterations with no mutations to new species.
#'
#'
#'
#' @noRd
#'
NULL

#' Multiple trials for a given set of parameter values.
#'
#' @inheritParams quantgen_trials
#'
#' @noRd
#'
quantgen_trials_ <- function(n_trials, N0, P0, V0, U0, r, a, f, b, c, m, g, etaN, etaP, sig2N, sig2P, delta, delta2, start_t, max_t, density_threshold, precision, n_cores, show_progress, return_every) {
    .Call(`_quantgenCR_quantgen_trials_`, n_trials, N0, P0, V0, U0, r, a, f, b, c, m, g, etaN, etaP, sig2N, sig2P, delta, delta2, start_t, max_t, density_threshold, precision, n_cores, show_progress, return_every)
}

