# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Search for unique species in a matrix of species trait values.
#'
#' @noRd
#'
NULL

#' Strength of selection for traits `V`, ones for resources
#'
#'
#' @noRd
#'
NULL

#' Sets matrix of traits for each resource (<# resources> x <# resources' traits>)
#'
#' @noRd
#'
NULL

#' Strength of selection for traits `U`, ones for consumers
#'
#'
#' @noRd
#'
NULL

#' Sets traits for each consumer (<# consumers> x <# consumers' traits>)
#'
#'
#' @noRd
#'
NULL

#' One trial of iterations with no mutations to new species.
#'
#'
#'
#' @noRd
#'
NULL

#' Multiple trials for a given set of parameter values.
#'
#' @param n_trials Number of trials to perform.
#' @param N0 Vector containing the starting abundance(s) for each resource.
#' @param P0 Vector containing the starting abundance(s) for each consumer.
#' @param V0 Matrix containing the starting trait value(s) for each resource.
#'     Each row refers to a particular resource.
#' @param U0 Matrix containing the starting trait value(s) for each consumer.
#'     Each row refers to a particular consumer.
#' @param r Base growth rate for resources.
#' @param a Baseline competition coefficient for resources.
#' @param f Cost of defensive traits for resources.
#' @param b Coefficient for attack rate of consumers on resources.
#' @param c Base growth rate for consumers.
#' @param m Mortality rate for consumers.
#' @param g Cost of offensive traits for consumers.
#' @param etaN Non-additive effect of increasing 2+ traits for resources.
#' @param etaP Non-additive effect of increasing 2+ traits for consumers.
#' @param sig2N Additive genetic variance for resources.
#' @param sig2P Additive genetic variance for consumers.
#' @param delta SD for log-normal distribution generating perturbation after the
#'     starting time steps.
#' @param delta2 SD for log-normal distribution generating perturbation at the
#'     halfway point in the primary time steps.
#' @param start_t Number of starting time steps.
#' @param max_t Number of primary time steps.
#' @param density_threshold Threshold for extinction. Defaults to `1e-5`.
#' @param precision Threshold for considering rows of traits to be the same.
#'     Defaults to `1e-2`.
#' @param n_cores Number of cores to use for processing.
#'     Ignored if not compiled using OpenMP. Defaults to `1`.
#' @param show_progress Boolean for whether to show a progress bar. Defaults to `TRUE`.
#' @param return_every Integer specifing the number of iterations (after the starting
#'     iterations) at which to output values of abundances and trait values.
#'     Values <= 0 mean that only final values are output.
#'     NOTE: A high value of `max_t` and a low value of `return_every` will result in
#'     a massive object being output.
#'     Defaults to `0`.
#'
#' @return A list containing the following components:
#' * `resource`: Info for resource(s).
#' * `consumer`: Info for consumer(s).
#'
#' Both `resource` and `consumer` have the same structure:
#'
#' * If `return_every <= 0`, a matrix with the following columns (in order):
#'     * The trial number
#'     * The final fitness
#'     * The final selection pressure
#'     * The final trait values (1 column for each trait)
#' * If `return_every > 0`, a list with the following items:
#'     * `final`: Matrix of final values for each trial (just like if
#'       `return_every <= 0`).
#'     * `past_abund`: A list of matrices (one for each trial).
#'       Each matrix contains species abundances through time,
#'       where rows are species and columns are time.
#'     * `past_traits`: A list of 3D arrays (one for each rial).
#'       Each array contains species traits through time,
#'       where rows are species, columns are traits, "slices" are time.
#'
#' @export
#'
quantgen_trials <- function(n_trials, N0, P0, V0, U0, r, a, f, b, c, m, g, etaN, etaP, sig2N, sig2P, delta, delta2, start_t, max_t, density_threshold = 1e-5, precision = 1e-2, n_cores = 1L, show_progress = TRUE, return_every = 0L) {
    .Call(`_quantgenCR_quantgen_trials`, n_trials, N0, P0, V0, U0, r, a, f, b, c, m, g, etaN, etaP, sig2N, sig2P, delta, delta2, start_t, max_t, density_threshold, precision, n_cores, show_progress, return_every)
}

